export type RoadmapStatus = 'planned' | 'in-progress' | 'completed';
export type Priority = 'high' | 'medium' | 'low';
export type ResourceType = 'doc' | 'video' | 'course' | 'article' | 'github';

export interface Subtask {
  id: string;
  title: string;
  description?: string;
  status: RoadmapStatus;
  order: number;
}

export interface Resource {
  title: string;
  url: string;
  type: ResourceType;
  completed?: boolean;
}

export interface Progress {
  percentage: number;
  totalHours?: number;
  completedHours?: number;
  lastUpdated?: string;
}

export interface RoadmapItem {
  id: string;
  title: string;
  description: string;
  category: string;
  subcategory?: string;
  status: RoadmapStatus;
  priority?: Priority;
  startDate?: string;
  targetDate?: string;
  tags?: string[];
  hidden?: boolean; // Hide from public view (admin only)

  // Relationships between Learning and COO Work
  relatedWorkIds?: string[]; // For Learning items: which COO Work items use this knowledge
  relatedLearningIds?: string[]; // For COO Work items: which Learning items support this work

  // Private tracking fields (for admin only, not shown publicly)
  progress?: Progress;
  subtasks?: Subtask[];
  resources?: Resource[];
  notes?: string;
}

// 🎓 Learning Roadmap - Knowledge COO needs to LEARN
export const learningRoadmap: RoadmapItem[] = [
  // === 1. GIAO TIẾP & GIỌNG NÓI ===
  {
    id: 'voice-training-learning',
    title: 'Voice Training tại THALIC VOICE',
    description: 'Học luyện giọng, cải thiện phát âm, giảm giọng địa phương cho giao tiếp chuyên nghiệp với khách hàng Nhật Bản',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Luyện Giọng & Phát Âm',
    status: 'planned',
    hidden: true,
    priority: 'high',
    startDate: '2025-11-01',
    tags: ['voice', 'communication', 'japanese-client'],
    notes: 'Đang học các bài tập về phát âm và hơi thở. Có thể viết bài chia sẻ trải nghiệm, bài tập thực tế, thách thức, cải thiện',
  },
  {
    id: 'breathing-techniques-learning',
    title: 'Kỹ thuật thở cho speaking',
    description: 'Học các kỹ thuật thở giúp nói rõ ràng, tự tin và kiểm soát giọng tốt hơn',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Luyện Giọng & Phát Âm',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['voice', 'breathing', 'speaking'],
  },
  {
    id: 'articulation-exercises-learning',
    title: 'Bài tập articulation',
    description: 'Luyện tập phát âm rõ ràng từng từ và câu',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Luyện Giọng & Phát Âm',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['articulation', 'pronunciation'],
  },
  {
    id: 'japanese-client-communication-learning',
    title: 'Giao tiếp với khách hàng Nhật Bản',
    description: 'Học nghi thức email, quy tắc meeting, văn hóa giao tiếp, trao đổi danh thiếp',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Giao Tiếp Chuyên Nghiệp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['japanese-business', 'culture', 'etiquette'],
    relatedWorkIds: ['japanese-client-relations-work'],
  },
  {
    id: 'written-communication-learning',
    title: 'Kỹ năng giao tiếp văn bản',
    description: 'Học cách viết email, báo cáo, tài liệu chuyên nghiệp',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Giao Tiếp Chuyên Nghiệp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['writing', 'email', 'documentation'],
  },
  {
    id: 'difficult-conversations-learning',
    title: 'Cuộc trò chuyện khó khăn',
    description: 'Học cách xử lý các cuộc trò chuyện nhạy cảm, feedback khó, đàm phán phức tạp',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Giao Tiếp Chuyên Nghiệp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['feedback', 'negotiation', 'conflict'],
  },
  {
    id: 'executive-presentation-learning',
    title: 'Kỹ năng thuyết trình cho C-level',
    description: 'Học cách thuyết trình hiệu quả với ban lãnh đạo, đối tác cấp cao',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Thuyết Trình & Nói Trước Công Chúng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['presentation', 'executive', 'public-speaking'],
  },
  {
    id: 'executive-communication-learning',
    title: 'Giao tiếp cấp điều hành',
    description: 'Học cách giao tiếp súc tích, rõ ràng với CEO, BOD và các C-level khác',
    category: 'Giao Tiếp & Giọng Nói',
    subcategory: 'Thuyết Trình & Nói Trước Công Chúng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['executive', 'c-level', 'leadership'],
  },

  // === 2. QUẢN TRỊ NHÂN SỰ ===
  {
    id: 'performance-evaluation-framework-learning',
    title: 'Hệ thống đánh giá hiệu suất',
    description: 'Học xây dựng framework đánh giá cho leaders, infrastructure engineers, tích hợp với KPI từ Redmine',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'high',
    startDate: '2025-10-01',
    tags: ['performance', 'kpi', 'evaluation', 'redmine'],
    relatedWorkIds: ['performance-review-process-work', 'redmine-kpi-system-work'],
    notes: 'Đã xác định tiêu chí đánh giá, cơ chế feedback. Có thể viết bài về cấu trúc framework, thiết kế KPI, tiêu chí đánh giá cho từng role',
  },
  {
    id: 'goal-setting-okr-learning',
    title: 'Đặt mục tiêu với OKR/SMART',
    description: 'Học các framework đặt mục tiêu hiệu quả cho team và cá nhân',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['okr', 'smart', 'goal-setting'],
  },
  {
    id: 'career-development-learning',
    title: 'Lộ trình phát triển nghề nghiệp',
    description: 'Học cách thiết kế career paths rõ ràng cho các roles khác nhau',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['career', 'development', 'growth'],
  },
  {
    id: 'team-building-culture-learning',
    title: 'Team building & văn hóa doanh nghiệp',
    description: 'Học cách xây dựng team cohesive và văn hóa công ty mạnh mẽ',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xây Dựng Team & Văn Hóa',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['culture', 'team-building', 'engagement'],
    relatedWorkIds: ['team-building-activities-work', 'culture-initiatives-work'],
  },
  {
    id: 'onboarding-process-learning',
    title: 'Thiết kế quy trình onboarding',
    description: 'Học cách tạo trải nghiệm onboarding tốt giúp nhân viên mới hòa nhập nhanh',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xây Dựng Team & Văn Hóa',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['onboarding', 'hiring', 'retention'],
  },
  {
    id: 'employee-engagement-learning',
    title: 'Gắn kết và giữ chân nhân viên',
    description: 'Học các chiến lược tăng engagement, giảm turnover',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xây Dựng Team & Văn Hóa',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['engagement', 'retention', 'culture'],
    relatedWorkIds: ['employee-engagement-programs-work', 'thanks-bonus-program-work'],
  },
  {
    id: 'conflict-resolution-learning',
    title: 'Giải quyết xung đột trong team',
    description: 'Học cách xử lý xung đột một cách hiệu quả, tạo môi trường làm việc tích cực',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xung Đột & Giao Tiếp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['conflict', 'mediation', 'team'],
  },
  {
    id: 'coaching-mentoring-learning',
    title: 'Coaching & mentoring',
    description: 'Học kỹ năng coaching và mentoring để phát triển team members',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xung Đột & Giao Tiếp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['coaching', 'mentoring', 'development'],
  },
  {
    id: 'psychological-safety-learning',
    title: 'Tạo môi trường an toàn tâm lý',
    description: 'Học cách xây dựng môi trường nơi mọi người cảm thấy an toàn khi chia sẻ ý kiến, sai lầm',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xung Đột & Giao Tiếp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['psychological-safety', 'culture', 'feedback'],
  },
  {
    id: 'emotional-intelligence-learning',
    title: 'Trí tuệ cảm xúc (EQ)',
    description: 'Học cách nhận diện và quản lý cảm xúc của bản thân và người khác',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Xung Đột & Giao Tiếp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['emotional-intelligence', 'eq', 'self-awareness', 'empathy'],
  },
  {
    id: 'change-leadership-learning',
    title: 'Dẫn dắt team qua thay đổi',
    description: 'Học cách dẫn dắt team qua các giai đoạn thay đổi, chuyển đổi lớn',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Ảnh Hưởng & Hợp Tác',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['change-management', 'transformation', 'leadership'],
  },
  {
    id: 'stakeholder-management-learning',
    title: 'Quản lý các bên liên quan',
    description: 'Học cách quản lý kỳ vọng và mối quan hệ với các bên liên quan',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Ảnh Hưởng & Hợp Tác',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['stakeholder', 'relationship', 'expectation'],
  },
  {
    id: 'cross-functional-leadership-learning',
    title: 'Lãnh đạo liên chức năng',
    description: 'Học cách làm việc hiệu quả với các departments khác nhau',
    category: 'Quản Trị Nhân Sự',
    subcategory: 'Ảnh Hưởng & Hợp Tác',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['cross-functional', 'collaboration', 'leadership'],
  },

  // === 3. CÔNG NGHỆ & ĐỔI MỚI ===
  {
    id: 'ai-ml-workflow-automation-learning',
    title: 'AI/ML cho tự động hóa workflow',
    description: 'Học về multi-agent orchestration, tích hợp Redmine + GitLab + Mattermost',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'AI/ML & Tự Động Hóa',
    status: 'planned',
    hidden: true,
    priority: 'high',
    startDate: '2025-09-01',
    tags: ['ai', 'ml', 'automation', 'multi-agent'],
    relatedWorkIds: ['ai-workflow-management-work'],
    notes: 'Đang nghiên cứu kiến trúc, pilot use cases. Có thể viết bài về thiết kế kiến trúc, use cases cụ thể, phân tích ROI',
  },
  {
    id: 'ai-roadmap-learning',
    title: 'Roadmap áp dụng AI',
    description: 'Học cách xây dựng roadmap áp dụng AI vào operations',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'AI/ML & Tự Động Hóa',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['ai', 'roadmap', 'strategy'],
  },
  {
    id: 'prompt-engineering-learning',
    title: 'Prompt engineering cho công việc COO',
    description: 'Học cách viết prompts hiệu quả để tối ưu công việc hàng ngày',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'AI/ML & Tự Động Hóa',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['prompt-engineering', 'ai', 'productivity'],
  },
  {
    id: 'devops-best-practices-learning',
    title: 'DevOps & CI/CD best practices',
    description: 'Học GitLab workflows, branch strategies, code review, deployment automation',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'DevOps & Hạ Tầng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['devops', 'ci-cd', 'gitlab', 'automation'],
    relatedWorkIds: ['devops-optimization-work'],
    notes: 'Đã triển khai chiến lược quản lý branch, quy trình code review. Có thể viết bài về GitLab workflow cho team, chiến lược branch',
  },
  {
    id: 'cloud-computing-learning',
    title: 'Chuyển đổi lên cloud computing',
    description: 'Học các cloud platforms (AWS, Azure, GCP), migration strategies',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'Cloud & Bảo Mật',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['cloud', 'aws', 'azure', 'gcp'],
  },
  {
    id: 'iso27001-cybersecurity-learning',
    title: 'Cybersecurity & ISO 27001',
    description: 'Học duy trì ISO 27001 compliance, chuẩn bị audit bảo mật, quy trình phản ứng sự cố',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'Cloud & Bảo Mật',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['iso27001', 'security', 'compliance', 'audit'],
    relatedWorkIds: ['iso27001-compliance-work'],
    notes: 'Đang duy trì compliance, chu kỳ tái chứng nhận hàng năm. Có thể viết bài về quy trình tuân thủ, tips chuẩn bị audit',
  },
  {
    id: 'information-security-management-learning',
    title: 'Quản lý bảo mật thông tin',
    description: 'Học cách quản lý bảo mật thông tin, data privacy, access control',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'Cloud & Bảo Mật',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['information-security', 'data-privacy', 'access-control'],
  },
  {
    id: 'corporate-compliance-learning',
    title: 'Corporate compliance & governance',
    description: 'Học về corporate compliance, internal controls, audit trails',
    category: 'Công Nghệ & Đổi Mới',
    subcategory: 'Cloud & Bảo Mật',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['compliance', 'governance', 'internal-controls'],
  },

  // === 4. VẬN HÀNH & QUY TRÌNH ===
  {
    id: 'quality-assurance-system-learning',
    title: 'Hệ thống đảm bảo chất lượng',
    description: 'Học cách xây dựng và duy trì QA processes, quality gates',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Đảm Bảo Chất Lượng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['qa', 'quality', 'testing'],
  },
  {
    id: 'it-project-management-learning',
    title: 'Quản lý dự án cho IT outsourcing',
    description: 'Học methodologies (Agile, Scrum, Waterfall), best practices cho outsourcing',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['project-management', 'agile', 'scrum', 'outsourcing'],
    relatedWorkIds: ['est-vs-actual-tracking-work', 'weekly-reporting-system-work', 'change-request-management-work'],
  },
  {
    id: 'portfolio-management-learning',
    title: 'Quản lý danh mục dự án',
    description: 'Học cách quản lý nhiều projects cùng lúc, ưu tiên resources',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['portfolio', 'prioritization', 'resource-allocation'],
  },
  {
    id: 'resource-planning-learning',
    title: 'Phân bổ nguồn lực',
    description: 'Học cách dự báo và phân bổ nguồn lực hiệu quả',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Nguồn Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['resource-planning', 'capacity', 'allocation'],
  },
  {
    id: 'vendor-management-learning',
    title: 'Quản lý nhà cung cấp',
    description: 'Học cách lựa chọn, đàm phán, và quản lý vendors',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Nguồn Lực',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['vendor', 'procurement', 'contracts'],
  },
  {
    id: 'service-excellence-learning',
    title: 'Đảm bảo chất lượng dịch vụ',
    description: 'Học các frameworks đảm bảo chất lượng dịch vụ cao',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['service-delivery', 'excellence', 'quality'],
  },
  {
    id: 'sla-slo-management-learning',
    title: 'Thiết kế & quản lý SLA/SLO',
    description: 'Học cách định nghĩa và theo dõi Service Level Agreements và Objectives',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['sla', 'slo', 'service-level'],
    relatedWorkIds: ['sla-compliance-tracking-work', 'sla-reporting-work', 'sla-performance-improvement-work'],
  },
  {
    id: 'escalation-management-learning',
    title: 'Quản lý leo thang vấn đề',
    description: 'Học cách xử lý escalations, quy trình phản ứng nhanh',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['escalation', 'incident', 'response'],
    relatedWorkIds: ['escalation-process-work', 'critical-issue-resolution-work', 'major-escalation-handling-work'],
  },
  {
    id: 'post-mortem-process-learning',
    title: 'Quy trình rút kinh nghiệm sau sự cố',
    description: 'Học cách chạy post-mortems hiệu quả, học từ failures',
    category: 'Vận Hành & Quy Trình',
    subcategory: 'Quản Lý Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['post-mortem', 'incident', 'learning'],
  },

  // === 5. KINH DOANH & CHIẾN LƯỢC ===
  {
    id: 'strategic-planning-frameworks-learning',
    title: 'Công cụ hoạch định chiến lược',
    description: 'Học các frameworks như Porter Five Forces, SWOT, Blue Ocean',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Lập Kế Hoạch Chiến Lược',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['strategy', 'frameworks', 'planning'],
    relatedWorkIds: ['annual-operating-plan-work', 'quarterly-okr-work'],
  },
  {
    id: 'scenario-planning-learning',
    title: 'Kế hoạch kịch bản',
    description: 'Học cách chuẩn bị cho nhiều tình huống tương lai khác nhau',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Lập Kế Hoạch Chiến Lược',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['scenario-planning', 'contingency', 'risk'],
  },
  {
    id: 'partnership-development-learning',
    title: 'Phát triển đối tác',
    description: 'Học cách đánh giá, đàm phán và xây dựng partnerships (ví dụ: VTI Academy)',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Phát Triển Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    startDate: '2025-10-01',
    tags: ['partnership', 'business-development', 'recruitment'],
    relatedWorkIds: ['vti-academy-partnership-work'],
    notes: 'Đang khám phá đối tác với VTI Academy. Mục tiêu ký MOU Q1/2026. Có thể viết bài về tiêu chí đánh giá đối tác, cách tiếp cận đàm phán',
  },
  {
    id: 'market-analysis-learning',
    title: 'Phân tích & định vị thị trường',
    description: 'Học cách phân tích thị trường, cạnh tranh, tìm positioning tốt nhất',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Phát Triển Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['market-analysis', 'positioning', 'competition'],
  },
  {
    id: 'service-expansion-learning',
    title: 'Mở rộng dịch vụ',
    description: 'Học cách mở rộng service offerings một cách có chiến lược',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Phát Triển Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['expansion', 'growth', 'services'],
  },
  {
    id: 'financial-management-coo-learning',
    title: 'Quản lý tài chính cho COO',
    description: 'Học cơ bản về quản lý tài chính, P&L, budgeting',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Quản Lý Tài Chính',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['finance', 'p&l', 'budget'],
    relatedWorkIds: ['pl-ownership-work', 'annual-budget-planning-work'],
  },
  {
    id: 'investment-decisions-learning',
    title: 'Quyết định đầu tư',
    description: 'Học cách đánh giá ROI, NPV cho các quyết định đầu tư',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Quản Lý Tài Chính',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['investment', 'roi', 'npv'],
  },
  {
    id: 'customer-health-score-learning',
    title: 'Điểm số sức khỏe khách hàng',
    description: 'Học cách đo lường và cải thiện customer health',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Customer Success',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['customer-success', 'health-score', 'retention'],
  },
  {
    id: 'churn-analysis-learning',
    title: 'Phân tích churn',
    description: 'Học cách phân tích và giảm churn rate',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Customer Success',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['churn', 'retention', 'analysis'],
  },
  {
    id: 'upsell-expansion-learning',
    title: 'Upsell và mở rộng doanh thu',
    description: 'Học cách tăng revenue từ khách hàng hiện tại',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Customer Success',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['upsell', 'expansion', 'growth'],
  },
  {
    id: 'customer-lifecycle-learning',
    title: 'Quản lý vòng đời khách hàng',
    description: 'Học cách quản lý customer journey từ acquisition đến renewal',
    category: 'Kinh Doanh & Chiến Lược',
    subcategory: 'Customer Success',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['customer-lifecycle', 'journey', 'retention'],
  },

  // === 6. QUẢN LÝ THỜI GIAN & RA QUYẾT ĐỊNH ===
  {
    id: 'time-management-executive-learning',
    title: 'Time management cho C-level',
    description: 'Học cách quản lý thời gian hiệu quả ở cấp điều hành',
    category: 'Quản Lý Thời Gian & Ra Quyết Định',
    subcategory: 'Quản Lý Thời Gian',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['time-management', 'productivity', 'executive'],
  },
  {
    id: 'decision-making-uncertainty-learning',
    title: 'Ra quyết định trong tình huống không chắc chắn',
    description: 'Học frameworks ra quyết định khi thiếu thông tin đầy đủ',
    category: 'Quản Lý Thời Gian & Ra Quyết Định',
    subcategory: 'Ra Quyết Định',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['decision-making', 'uncertainty', 'frameworks'],
  },

  // === 7. TÀI CHÍNH & THƯƠNG MẠI ===
  {
    id: 'pl-management-learning',
    title: 'Quản lý P&L cho COO',
    description: 'Học cách quản lý P&L, trách nhiệm về lợi nhuận',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['p&l', 'profit', 'loss'],
  },
  {
    id: 'financial-statements-learning',
    title: 'Đọc hiểu báo cáo tài chính',
    description: 'Học cách đọc và phân tích báo cáo tài chính (Balance Sheet, Income Statement, Cash Flow)',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['financial-statements', 'accounting', 'analysis'],
  },
  {
    id: 'profit-accountability-learning',
    title: 'Chịu trách nhiệm về lợi nhuận',
    description: 'Học cách chịu trách nhiệm về profitability của operations',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['profitability', 'accountability', 'margins'],
  },
  {
    id: 'budget-planning-learning',
    title: 'Quản lý & kiểm soát ngân sách',
    description: 'Học cách lập và theo dõi budget',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý Ngân Sách',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['budget', 'planning', 'control'],
  },
  {
    id: 'cost-optimization-learning',
    title: 'Tối ưu hóa chi phí',
    description: 'Học cách giảm chi phí mà không ảnh hưởng chất lượng',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý Ngân Sách',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['cost-optimization', 'efficiency', 'savings'],
  },
  {
    id: 'financial-forecasting-learning',
    title: 'Dự báo tài chính',
    description: 'Học cách dự báo revenue và costs',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý Ngân Sách',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['forecasting', 'revenue', 'costs'],
  },
  {
    id: 'cash-flow-management-learning',
    title: 'Quản lý cash flow',
    description: 'Học cách quản lý dòng tiền để đảm bảo thanh khoản',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Quản Lý Ngân Sách',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['cash-flow', 'liquidity', 'working-capital'],
    relatedWorkIds: ['cash-flow-management-work'],
  },
  {
    id: 'pricing-strategy-learning',
    title: 'Phương pháp định giá',
    description: 'Học các frameworks định giá (value-based, cost-plus, competitive)',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['pricing', 'strategy', 'value'],
  },
  {
    id: 'unit-economics-learning',
    title: 'Phân tích unit economics',
    description: 'Học cách phân tích profitability ở mức unit (per engineer, per project)',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['unit-economics', 'profitability', 'metrics'],
  },
  {
    id: 'project-profitability-learning',
    title: 'Phân tích lợi nhuận theo dự án',
    description: 'Học cách đo lường và cải thiện project profitability',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['project-profitability', 'margins', 'analysis'],
  },
  {
    id: 'pricing-decisions-learning',
    title: 'Quyết định về pricing',
    description: 'Học cách ra quyết định pricing cho projects và services',
    category: 'Tài Chính & Thương Mại',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['pricing', 'decision-making', 'negotiation'],
  },

  // === 8. RỦI RO & QUẢN LÝ KHỦNG HOẢNG ===
  {
    id: 'enterprise-risk-management-learning',
    title: 'Enterprise Risk Management (ERM)',
    description: 'Học frameworks quản lý rủi ro ở cấp doanh nghiệp',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['risk', 'erm', 'framework'],
  },
  {
    id: 'risk-assessment-learning',
    title: 'Đánh giá & giảm thiểu rủi ro',
    description: 'Học cách xác định, đánh giá và giảm thiểu rủi ro',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['risk-assessment', 'mitigation', 'analysis'],
  },
  {
    id: 'insurance-liability-learning',
    title: 'Quản lý bảo hiểm & trách nhiệm pháp lý',
    description: 'Học về các loại bảo hiểm cần thiết và quản lý liability',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['insurance', 'liability', 'risk'],
  },
  {
    id: 'business-continuity-planning-learning',
    title: 'Kế hoạch liên tục kinh doanh (BCP)',
    description: 'Học cách xây dựng và duy trì BCP',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['bcp', 'continuity', 'disaster-recovery'],
    relatedWorkIds: ['bcp-plan-work'],
  },
  {
    id: 'crisis-management-learning',
    title: 'Quản lý và xử lý khủng hoảng',
    description: 'Học cách xử lý khủng hoảng một cách hiệu quả',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['crisis', 'emergency', 'response'],
    relatedWorkIds: ['crisis-response-protocol-work', 'crisis-communication-work'],
  },
  {
    id: 'disaster-recovery-learning',
    title: 'Kế hoạch phục hồi sau thảm họa (DR)',
    description: 'Học cách xây dựng disaster recovery plans',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['disaster-recovery', 'dr', 'backup'],
    relatedWorkIds: ['dr-plan-work'],
  },
  {
    id: 'crisis-scenario-planning-learning',
    title: 'Kế hoạch kịch bản khủng hoảng',
    description: 'Học cách chuẩn bị cho các scenarios khủng hoảng khác nhau',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['crisis', 'scenario-planning', 'preparation'],
  },
  {
    id: 'crisis-communication-learning',
    title: 'Giao tiếp trong khủng hoảng',
    description: 'Học cách giao tiếp hiệu quả trong khủng hoảng với teams, clients, stakeholders',
    category: 'Rủi Ro & Quản Lý Khủng Hoảng',
    subcategory: 'Quản Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['crisis-communication', 'stakeholder', 'transparency'],
  },

  // === 9. CHUYỂN ĐỔI & ĐỔI MỚI ===
  {
    id: 'change-communication-learning',
    title: 'Giao tiếp về thay đổi tổ chức',
    description: 'Học cách giao tiếp về thay đổi để tăng acceptance',
    category: 'Chuyển Đổi & Đổi Mới',
    subcategory: 'Lãnh Đạo Thay Đổi',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['change', 'communication', 'adoption'],
  },
  {
    id: 'change-resistance-learning',
    title: 'Xử lý phản ứng với thay đổi',
    description: 'Học cách xử lý resistance to change',
    category: 'Chuyển Đổi & Đổi Mới',
    subcategory: 'Lãnh Đạo Thay Đổi',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['change', 'resistance', 'adoption'],
  },
  {
    id: 'digital-transformation-learning',
    title: 'Dẫn dắt chuyển đổi số',
    description: 'Học cách dẫn dắt digital transformation',
    category: 'Chuyển Đổi & Đổi Mới',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['digital-transformation', 'technology', 'change'],
  },
  {
    id: 'process-change-management-learning',
    title: 'Thay đổi quy trình làm việc',
    description: 'Học cách thay đổi quy trình mà không gây gián đoạn',
    category: 'Chuyển Đổi & Đổi Mới',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['process', 'change', 'optimization'],
  },

  // === 10. LẬP KẾ HOẠCH NĂNG LỰC & DỰ BÁO ===
  {
    id: 'demand-forecasting-learning',
    title: 'Phương pháp dự báo nhu cầu',
    description: 'Học các phương pháp dự báo demand cho resources',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['demand-forecasting', 'capacity', 'planning'],
    relatedWorkIds: ['quarterly-demand-forecast-work', 'pipeline-analysis-work'],
  },
  {
    id: 'pipeline-analysis-learning',
    title: 'Pipeline analysis',
    description: 'Học cách phân tích sales/project pipeline để dự báo',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['pipeline', 'analysis', 'forecasting'],
  },
  {
    id: 'seasonal-planning-learning',
    title: 'Seasonal planning',
    description: 'Học cách lập kế hoạch cho các biến động theo mùa',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['seasonal', 'planning', 'demand'],
  },
  {
    id: 'capacity-modeling-learning',
    title: 'Capacity modeling',
    description: 'Học cách model capacity để đáp ứng demand',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['capacity', 'modeling', 'planning'],
    relatedWorkIds: ['capacity-models-work', 'utilization-tracking-work'],
  },
  {
    id: 'utilization-optimization-learning',
    title: 'Tối ưu tỷ lệ sử dụng nguồn lực',
    description: 'Học cách tối ưu tỷ lệ sử dụng nguồn lực mà không burn out team',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['utilization', 'optimization', 'capacity'],
  },
  {
    id: 'bench-management-learning',
    title: 'Quản lý nguồn lực dự phòng',
    description: 'Học cách quản lý nguồn lực dự phòng (bench) hiệu quả',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['bench', 'idle-resources', 'planning'],
  },
  {
    id: 'hiring-forecast-learning',
    title: 'Dự báo tuyển dụng',
    description: 'Học cách dự báo hiring needs dựa trên pipeline và attrition',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['hiring', 'forecasting', 'recruitment'],
  },

  // === 11. HỢP ĐỒNG & PHÁP LÝ ===
  {
    id: 'contract-negotiation-learning',
    title: 'Kỹ thuật đàm phán hợp đồng',
    description: 'Học cách đàm phán hợp đồng có lợi cho cả hai bên',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Đàm Phán Hợp Đồng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['contract', 'negotiation', 'legal'],
    relatedWorkIds: ['client-contract-negotiation-work', 'vendor-contract-negotiation-work', 'terms-conditions-negotiation-work'],
  },
  {
    id: 'contract-structure-learning',
    title: 'Cấu trúc hợp đồng',
    description: 'Học các loại hợp đồng, điều khoản quan trọng cần chú ý',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Đàm Phán Hợp Đồng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['contract', 'structure', 'terms'],
  },
  {
    id: 'msa-sow-frameworks-learning',
    title: 'Quản lý MSA/SOW',
    description: 'Học về Master Service Agreements và Statements of Work',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Đàm Phán Hợp Đồng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['msa', 'sow', 'contracts'],
  },
  {
    id: 'legal-risk-management-learning',
    title: 'Quản lý rủi ro pháp lý',
    description: 'Học cách xác định và quản lý legal risks',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Quản Lý Rủi Ro Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['legal', 'risk', 'compliance'],
  },
  {
    id: 'ip-nda-protection-learning',
    title: 'Bảo vệ IP & NDA',
    description: 'Học về Intellectual Property protection và NDAs',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Quản Lý Rủi Ro Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['ip', 'nda', 'confidentiality'],
  },
  {
    id: 'labor-law-compliance-learning',
    title: 'Tuân thủ luật lao động',
    description: 'Học về các yêu cầu tuân thủ luật lao động',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Quản Lý Rủi Ro Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['labor-law', 'compliance', 'hr'],
  },
  {
    id: 'dispute-resolution-learning',
    title: 'Giải quyết tranh chấp',
    description: 'Học các phương pháp giải quyết tranh chấp (mediation, arbitration)',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Quản Lý Rủi Ro Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['dispute', 'resolution', 'legal'],
  },

  // === 12. DATA & ANALYTICS ===
  {
    id: 'business-intelligence-learning',
    title: 'Business Intelligence',
    description: 'Học cách xây dựng BI strategy cho operations',
    category: 'Data & Analytics',
    subcategory: 'Chiến Lược Data',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['bi', 'analytics', 'data'],
  },
  {
    id: 'data-driven-decisions-learning',
    title: 'Ra quyết định dựa trên data',
    description: 'Học cách sử dụng data để ra quyết định tốt hơn',
    category: 'Data & Analytics',
    subcategory: 'Chiến Lược Data',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['data-driven', 'decision-making', 'analytics'],
  },
  {
    id: 'data-governance-learning',
    title: 'Data governance',
    description: 'Học về data quality, security, privacy',
    category: 'Data & Analytics',
    subcategory: 'Chiến Lược Data',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['data-governance', 'quality', 'security'],
  },

  // === 13. PHÁT TRIỂN NHÂN SỰ ===
  {
    id: 'talent-acquisition-learning',
    title: 'Tuyển dụng nhân tài',
    description: 'Học cách xây dựng talent acquisition strategy',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['recruitment', 'talent', 'hiring'],
    relatedWorkIds: ['hiring-pipeline-management-work', 'pipeline-based-hiring-forecast-work', 'hiring-timing-decisions-work'],
  },
  {
    id: 'employer-branding-learning',
    title: 'Employer branding',
    description: 'Học cách xây dựng thương hiệu nhà tuyển dụng hấp dẫn',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['employer-brand', 'recruitment', 'marketing'],
  },
  {
    id: 'recruitment-funnel-learning',
    title: 'Tối ưu phễu tuyển dụng',
    description: 'Học cách tối ưu recruitment funnel để tăng conversion',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['recruitment', 'funnel', 'conversion'],
  },
  {
    id: 'interview-process-learning',
    title: 'Thiết kế quy trình phỏng vấn',
    description: 'Học cách thiết kế quy trình phỏng vấn hiệu quả, giảm bias',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['interview', 'hiring', 'assessment'],
  },
  {
    id: 'compensation-benchmarking-learning',
    title: 'Benchmarking lương',
    description: 'Học cách benchmark compensation với thị trường',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Lương & Phúc Lợi',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['compensation', 'benchmarking', 'market'],
  },
  {
    id: 'compensation-philosophy-learning',
    title: 'Triết lý compensation',
    description: 'Học cách xây dựng compensation philosophy',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Lương & Phúc Lợi',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['compensation', 'philosophy', 'strategy'],
  },
  {
    id: 'benefits-design-learning',
    title: 'Thiết kế benefits',
    description: 'Học cách thiết kế benefits package hấp dẫn',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Lương & Phúc Lợi',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['benefits', 'perks', 'retention'],
  },
  {
    id: 'bonus-incentive-learning',
    title: 'Cấu trúc bonus/incentive',
    description: 'Học cách thiết kế bonus và incentive structures',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Lương & Phúc Lợi',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['bonus', 'incentive', 'performance'],
  },
  {
    id: 'key-person-risk-learning',
    title: 'Rủi ro người then chốt',
    description: 'Học cách xác định và giảm thiểu key person risks',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Đào Tạo Kế Nhiệm',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['succession', 'risk', 'retention'],
  },
  {
    id: 'leadership-pipeline-learning',
    title: 'Pipeline lãnh đạo',
    description: 'Học cách xây dựng leadership pipeline',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Đào Tạo Kế Nhiệm',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['leadership', 'succession', 'development'],
  },
  {
    id: 'knowledge-transfer-learning',
    title: 'Chuyển giao kiến thức',
    description: 'Học cách đảm bảo knowledge transfer hiệu quả',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Đào Tạo Kế Nhiệm',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['knowledge-transfer', 'documentation', 'continuity'],
  },
  {
    id: 'critical-role-backup-learning',
    title: 'Backup cho vai trò quan trọng',
    description: 'Học cách chuẩn bị backup plans cho critical roles',
    category: 'Phát Triển Nhân Sự',
    subcategory: 'Đào Tạo Kế Nhiệm',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['backup', 'succession', 'continuity'],
  },
];

// 💼 COO Work Roadmap - Actual operational WORK being done
export const cooRoadmap: RoadmapItem[] = [
  // === 1. CHIẾN LƯỢC & THỰC THI ===
  {
    id: 'crud-to-ai-transition-work',
    title: 'Chuyển đổi từ CRUD sang AI/ML',
    description: 'Dẫn dắt transition từ traditional CRUD projects sang AI/ML và Cloud Computing services. Đã xác định 2-3 pilot projects, bắt đầu upskill engineers',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Chuyển Đổi Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    startDate: '2024-01-01',
    targetDate: '2026-12-31',
    tags: ['transformation', 'ai-ml', 'strategy', 'upskilling'],
    notes: 'Thách thức: Upskill team, giáo dục khách hàng, cách tiếp cận sales mới. Có thể viết bài về chiến lược transition, thách thức, cách tiếp cận upskilling',
  },
  {
    id: 'scaling-plan-work',
    title: 'Kế hoạch scale 20-30 người/năm',
    description: 'Xây dựng recruitment pipeline để scale từ 100 lên 120-130 vào cuối 2026. 40% experienced, 40% mid-level, 20% fresh graduates',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Chuyển Đổi Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['scaling', 'recruitment', 'growth', 'pipeline'],
    notes: 'Đã thảo luận partnership với VTI Academy. Có thể viết bài về chiến lược recruitment cho IT outsourcing, hiring mix, onboarding',
  },
  {
    id: 'service-expansion-work',
    title: 'Mở rộng dịch vụ sang AI/ML & Cloud',
    description: 'Triển khai chiến lược mở rộng từ CRUD sang AI/ML, Cloud services',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Chuyển Đổi Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['expansion', 'services', 'strategy'],
  },
  {
    id: 'annual-operating-plan-work',
    title: 'Phát triển kế hoạch vận hành hàng năm (AOP)',
    description: 'Lập và thực thi Annual Operating Plan',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Kế Hoạch Hàng Năm & Quý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['planning', 'aop', 'strategy'],
    relatedLearningIds: ['strategic-planning-frameworks-learning'],
  },
  {
    id: 'quarterly-okr-work',
    title: 'Thiết lập OKR hàng quý',
    description: 'Thiết lập và theo dõi OKRs cho organization',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Kế Hoạch Hàng Năm & Quý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['okr', 'goals', 'quarterly'],
    relatedLearningIds: ['strategic-planning-frameworks-learning'],
  },
  {
    id: 'competitive-analysis-work',
    title: 'Cập nhật phân tích cạnh tranh',
    description: 'Theo dõi và phân tích landscape cạnh tranh',
    category: 'Chiến Lược & Thực Thi',
    subcategory: 'Phân Tích Thị Trường',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['competition', 'market', 'analysis'],
  },

  // === 2. QUẢN LÝ TEAM (100+ NGƯỜI) ===
  {
    id: 'managing-11-teams-work',
    title: 'Quản lý 11 teams với 100+ người',
    description: 'Quản lý Engineering, Testing/QA, Comtor, PM, PQA, BA, Infrastructure, Design teams. 1-on-1 hàng tuần, all-hands hàng tháng',
    category: 'Quản Lý Team',
    subcategory: 'Quản Lý Nhiều Team',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['team-management', 'leadership', 'remote', 'culture'],
    notes: 'Thách thức: Giao tiếp giữa distributed teams, duy trì văn hóa remote. Có thể viết bài về cấu trúc teams, quản lý multiple teams, best practices 1-on-1',
  },
  {
    id: 'redmine-kpi-system-work',
    title: 'Hệ thống KPI từ Redmine',
    description: 'Xây dựng và duy trì hệ thống tracking KPI: EST vs Actual, velocity, bug rates, code review turnaround, client satisfaction',
    category: 'Quản Lý Team',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['kpi', 'redmine', 'metrics', 'tracking'],
    relatedLearningIds: ['performance-evaluation-framework-learning'],
    notes: 'Có thể viết bài về cách extract KPIs từ Redmine, metrics quan trọng cho IT outsourcing, thiết kế dashboard',
  },
  {
    id: 'performance-review-process-work',
    title: 'Quy trình đánh giá hiệu suất',
    description: 'Triển khai evaluation frameworks cho leaders, infrastructure engineers, PMs. Review nửa năm, 360-degree feedback cho leaders',
    category: 'Quản Lý Team',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['performance', 'evaluation', '360-feedback', 'calibration'],
    relatedLearningIds: ['performance-evaluation-framework-learning'],
    notes: 'Có thể viết bài về evaluation framework chi tiết cho từng role, triển khai 360 feedback, calibration sessions',
  },
  {
    id: 'training-development-work',
    title: 'Chương trình đào tạo & phát triển',
    description: 'Triển khai các chương trình đào tạo cho team members',
    category: 'Quản Lý Team',
    subcategory: 'Quản Lý Hiệu Suất',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['training', 'development', 'upskilling'],
  },
  {
    id: 'team-building-activities-work',
    title: 'Hoạt động team building',
    description: 'Tổ chức các hoạt động team building để tăng gắn kết',
    category: 'Quản Lý Team',
    subcategory: 'Văn Hóa Doanh Nghiệp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['team-building', 'engagement', 'culture'],
    relatedLearningIds: ['team-building-culture-learning'],
  },
  {
    id: 'feedback-mechanisms-work',
    title: 'Cơ chế feedback',
    description: 'Xây dựng và duy trì các cơ chế feedback liên tục',
    category: 'Quản Lý Team',
    subcategory: 'Văn Hóa Doanh Nghiệp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['feedback', 'communication', 'culture'],
  },

  // === 3. LÃNH ĐẠO CÔNG NGHỆ ===
  {
    id: 'ai-workflow-management-work',
    title: 'Quản lý workflow bằng AI',
    description: 'Triển khai hệ thống tích hợp Redmine + GitLab + Mattermost với AI agents. Automated status updates, PR review summaries, blocker detection',
    category: 'Lãnh Đạo Công Nghệ',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'high',
    targetDate: '2026-06-30',
    tags: ['ai', 'workflow', 'automation', 'integration'],
    relatedLearningIds: ['ai-ml-workflow-automation-learning'],
    notes: 'MVP Q1 2026, triển khai đầy đủ Q2 2026. ROI: giảm 20-30% overhead quản lý. Có thể viết bài về thiết kế kiến trúc chi tiết, use cases',
  },
  {
    id: 'devops-optimization-work',
    title: 'Tối ưu DevOps',
    description: 'Cải thiện GitLab CI/CD, branch strategies, deployment automation. Chuẩn hóa branch strategy, enforce automated testing',
    category: 'Lãnh Đạo Công Nghệ',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['devops', 'ci-cd', 'gitlab', 'automation'],
    relatedLearningIds: ['devops-best-practices-learning'],
    notes: 'Có thể viết bài về hành trình tối ưu CI/CD, quyết định branch strategy, automation wins, thách thức team adoption',
  },
  {
    id: 'pwa-initiatives-work',
    title: 'PWA development initiatives',
    description: 'Lead 2-3 PWA projects cho clients. Xây dựng chuyên môn PWA nội bộ, tài liệu hóa best practices',
    category: 'Lãnh Đạo Công Nghệ',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['pwa', 'offline-first', 'mobile', 'web'],
    notes: 'Có thể viết bài về lợi ích PWA cho clients, architecture patterns, thiết kế offline-first, thách thức, giáo dục khách hàng',
  },
  {
    id: 'tech-stack-modernization-work',
    title: 'Hiện đại hóa tech stack',
    description: 'Cập nhật và hiện đại hóa technology stack',
    category: 'Lãnh Đạo Công Nghệ',
    subcategory: 'Chuyển Đổi Số',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['technology', 'modernization', 'stack'],
  },
  {
    id: 'innovation-time-allocation-work',
    title: 'Phân bổ thời gian đổi mới',
    description: 'Phân bổ time cho R&D và innovation activities',
    category: 'Lãnh Đạo Công Nghệ',
    subcategory: 'Đổi Mới & R&D',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['innovation', 'r&d', 'time-allocation'],
  },

  // === 4. VẬN HÀNH & CHẤT LƯỢNG ===
  {
    id: 'iso27001-compliance-work',
    title: 'Tuân thủ ISO 27001',
    description: 'Duy trì ISO 27001 compliance, chuẩn bị audit bảo mật, quy trình phản ứng sự cố, chu kỳ tái chứng nhận hàng năm',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Kiểm Toán & Tuân Thủ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['iso27001', 'compliance', 'security', 'audit'],
    relatedLearningIds: ['iso27001-cybersecurity-learning'],
    notes: 'Có thể viết bài về quy trình tuân thủ ISO 27001, tips chuẩn bị audit, yêu cầu tài liệu, bài học từ các audits',
  },
  {
    id: 'gdpr-compliance-work',
    title: 'Tuân thủ GDPR/Bảo vệ dữ liệu',
    description: 'Đảm bảo tuân thủ GDPR và data protection regulations',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Kiểm Toán & Tuân Thủ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['gdpr', 'data-protection', 'compliance'],
  },
  {
    id: 'est-vs-actual-tracking-work',
    title: 'Tracking EST vs Actual',
    description: 'Theo dõi và phân tích estimates vs actuals cho tất cả projects. Báo cáo hàng tuần, phân tích variance, cảnh báo tự động cho >20% variance',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Vận Hành Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['estimation', 'tracking', 'variance', 'accuracy'],
    notes: 'Có thể viết bài về tại sao EST vs Actual quan trọng, cách track trong Redmine, cách tiếp cận phân tích variance',
    relatedLearningIds: ['it-project-management-learning'],
  },
  {
    id: 'weekly-reporting-system-work',
    title: 'Hệ thống báo cáo hàng tuần',
    description: 'Duy trì hệ thống reporting chuẩn hóa. Tự động tạo báo cáo từ Redmine, executive summary cho leadership, báo cáo status cho client',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Vận Hành Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['reporting', 'automation', 'transparency', 'communication'],
    notes: 'Có thể viết bài về thiết kế report template, cách tiếp cận automation, những gì cần đưa vào các loại report khác nhau',
    relatedLearningIds: ['it-project-management-learning'],
  },
  {
    id: 'change-request-management-work',
    title: 'Quản lý Change Request',
    description: 'Quản lý CR workflows. Quy trình tiếp nhận, đánh giá impact (scope, timeline, cost), approval workflows, kiểm tra capacity',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Vận Hành Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['change-request', 'scope', 'impact-assessment', 'approval'],
    notes: 'Có thể viết bài về thiết kế quy trình CR, framework đánh giá impact, tiêu chí approval, cách từ chối một cách nhẹ nhàng',
    relatedLearningIds: ['it-project-management-learning'],
  },
  {
    id: 'quality-metrics-improvement-work',
    title: 'Quality metrics & cải thiện',
    description: 'Theo dõi và cải thiện quality metrics',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Vận Hành Dự Án',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['quality', 'metrics', 'improvement'],
  },
  {
    id: 'process-documentation-work',
    title: 'Tài liệu hóa quy trình',
    description: 'Tài liệu hóa và chuẩn hóa các quy trình vận hành',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Cải Tiến Quy Trình',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['documentation', 'process', 'standardization'],
  },
  {
    id: 'automation-opportunities-work',
    title: 'Cơ hội tự động hóa',
    description: 'Xác định và triển khai automation opportunities',
    category: 'Vận Hành & Chất Lượng',
    subcategory: 'Cải Tiến Quy Trình',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['automation', 'efficiency', 'optimization'],
  },

  // === 5. PHÁT TRIỂN KINH DOANH ===
  {
    id: 'japanese-client-relations-work',
    title: 'Quan hệ khách hàng Nhật Bản',
    description: 'Duy trì và làm sâu quan hệ với khách hàng Nhật. QBRs định kỳ, quản lý tài khoản chủ động, khảo sát sự hài lòng',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Chăm Sóc Khách Hàng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['client-relations', 'japanese', 'qbr', 'account-management'],
    notes: 'Có thể viết bài về best practices quản lý khách hàng Nhật, cân nhắc văn hóa, cấu trúc QBR',
    relatedLearningIds: ['japanese-client-communication-learning'],
  },
  {
    id: 'customer-retention-strategy-work',
    title: 'Giữ chân khách hàng',
    description: 'Triển khai chiến lược retention để giảm churn',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Chăm Sóc Khách Hàng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['retention', 'churn', 'customer-success'],
  },
  {
    id: 'vti-academy-partnership-work',
    title: 'Partnership với VTI Academy',
    description: 'Khám phá đối tác với VTI Academy cho recruitment pipeline. Các mô hình: chương trình thực tập, tuyển dụng campus, khóa đào tạo đồng thương hiệu',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Đối Tác Chiến Lược',
    status: 'planned',
    hidden: true,
    priority: 'high',
    targetDate: '2026-03-31',
    tags: ['partnership', 'recruitment', 'academy', 'talent-pipeline'],
    relatedLearningIds: ['partnership-development-learning'],
    notes: 'Mục tiêu ký MOU Q1/2026. Có thể viết bài về tiêu chí đánh giá đối tác, cách tiếp cận đàm phán, mô hình đối tác',
  },
  {
    id: 'tech-conference-participation-work',
    title: 'Tham gia hội nghị công nghệ',
    description: 'Cân nhắc tham gia Tech4Life Expo. Đánh giá ROI (nhận diện thương hiệu, networking, thu hút nhân tài), cân nhắc booth vs speaking',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Đối Tác Chiến Lược',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['conference', 'branding', 'networking', 'recruitment'],
    notes: 'Có thể viết bài về cách đánh giá ROI hội nghị, booth setup vs speaking, chiến lược tạo leads',
  },
  {
    id: 'new-market-exploration-work',
    title: 'Khám phá thị trường mới',
    description: 'Nghiên cứu và khám phá các thị trường mới',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Đối Tác Chiến Lược',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['market', 'expansion', 'growth'],
  },
  {
    id: 'proposal-quality-work',
    title: 'Đảm bảo chất lượng đề xuất',
    description: 'Review và đảm bảo chất lượng proposals cho clients',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Hỗ Trợ Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['proposal', 'quality', 'sales'],
  },
  {
    id: 'presales-technical-support-work',
    title: 'Hỗ trợ kỹ thuật pre-sales',
    description: 'Hỗ trợ sales team với technical expertise',
    category: 'Phát Triển Kinh Doanh',
    subcategory: 'Hỗ Trợ Kinh Doanh',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['presales', 'technical', 'sales-support'],
  },

  // === 6. VĂN HÓA & GIAO TIẾP NỘI BỘ ===
  {
    id: 'thanks-bonus-program-work',
    title: 'Chương trình thanks bonus',
    description: 'Duy trì chương trình ghi nhận hàng tháng. Tiêu chí: Chất lượng, Đổi mới, Teamwork, Sự hài lòng của khách hàng. Đề cử từ đồng nghiệp',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Khen Thưởng & Ghi Nhận',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['recognition', 'bonus', 'culture', 'engagement'],
    notes: 'Có thể viết bài về thiết kế chương trình ghi nhận, định nghĩa tiêu chí, triển khai đề cử từ đồng nghiệp, impact lên văn hóa',
    relatedLearningIds: ['employee-engagement-learning'],
  },
  {
    id: 'service-awards-work',
    title: 'Giải thưởng làm việc lâu năm',
    description: 'Triển khai chương trình ghi nhận service milestones',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Khen Thưởng & Ghi Nhận',
    status: 'planned',
    hidden: true,
    priority: 'low',
    tags: ['recognition', 'retention', 'loyalty'],
  },
  {
    id: 'internal-communication-strategy-work',
    title: 'Giao tiếp nội bộ hiệu quả',
    description: 'Xây dựng và triển khai internal communication strategy',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Giao Tiếp Nội Bộ',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['communication', 'transparency', 'engagement'],
  },
  {
    id: 'all-hands-meetings-work',
    title: 'All-hands meetings',
    description: 'Tổ chức và dẫn dắt all-hands meetings định kỳ',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Giao Tiếp Nội Bộ',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['all-hands', 'communication', 'transparency'],
  },
  {
    id: 'culture-initiatives-work',
    title: 'Sáng kiến văn hóa công ty',
    description: 'Triển khai các sáng kiến để xây dựng văn hóa mạnh mẽ',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Văn Hóa Công Ty',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['culture', 'values', 'engagement'],
    relatedLearningIds: ['team-building-culture-learning'],
  },
  {
    id: 'employee-engagement-programs-work',
    title: 'Chương trình gắn kết nhân viên',
    description: 'Triển khai các chương trình tăng employee engagement',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Văn Hóa Công Ty',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['engagement', 'retention', 'culture'],
    relatedLearningIds: ['employee-engagement-learning'],
  },
  {
    id: 'remote-work-best-practices-work',
    title: 'Quản lý làm việc remote',
    description: 'Phát triển và triển khai remote work best practices',
    category: 'Văn Hóa & Giao Tiếp Nội Bộ',
    subcategory: 'Văn Hóa Công Ty',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['remote-work', 'best-practices', 'productivity'],
  },

  // === 7. QUẢN LÝ TÀI CHÍNH ===
  {
    id: 'pl-ownership-work',
    title: 'Sở hữu & báo cáo P&L',
    description: 'Chịu trách nhiệm về P&L, báo cáo financial performance',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['p&l', 'financial', 'accountability'],
    relatedLearningIds: ['financial-management-coo-learning'],
  },
  {
    id: 'revenue-profitability-analysis-work',
    title: 'Phân tích revenue & profitability',
    description: 'Phân tích revenue streams và profitability theo project, client',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['revenue', 'profitability', 'analysis'],
  },
  {
    id: 'margin-accountability-work',
    title: 'Chịu trách nhiệm về margin',
    description: 'Đảm bảo và cải thiện profit margins',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Quản Lý P&L',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['margin', 'profitability', 'optimization'],
  },
  {
    id: 'annual-budget-planning-work',
    title: 'Ngân sách hàng năm',
    description: 'Lập kế hoạch ngân sách hàng năm cho operations',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Ngân Sách & Kiểm Soát Chi Phí',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['budget', 'planning', 'annual'],
    relatedLearningIds: ['financial-management-coo-learning'],
  },
  {
    id: 'budget-tracking-control-work',
    title: 'Theo dõi & kiểm soát ngân sách',
    description: 'Theo dõi budget variance và kiểm soát spending',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Ngân Sách & Kiểm Soát Chi Phí',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['budget', 'control', 'variance'],
  },
  {
    id: 'cost-optimization-initiatives-work',
    title: 'Sáng kiến tối ưu chi phí',
    description: 'Triển khai các initiatives để tối ưu costs',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Ngân Sách & Kiểm Soát Chi Phí',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['cost', 'optimization', 'efficiency'],
  },
  {
    id: 'spending-approvals-work',
    title: 'Phê duyệt chi tiêu',
    description: 'Review và phê duyệt spending requests',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Ngân Sách & Kiểm Soát Chi Phí',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['approval', 'spending', 'control'],
  },
  {
    id: 'pricing-approval-work',
    title: 'Quyết định & phê duyệt pricing',
    description: 'Ra quyết định pricing cho projects và services',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['pricing', 'decision', 'approval'],
  },
  {
    id: 'project-profitability-analysis-work',
    title: 'Báo cáo lợi nhuận dự án',
    description: 'Phân tích profitability của từng project',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['project', 'profitability', 'analysis'],
  },
  {
    id: 'unit-economics-optimization-work',
    title: 'Tối ưu unit economics',
    description: 'Tối ưu economics ở mức unit (per engineer, per project)',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Định Giá & Lợi Nhuận',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['unit-economics', 'optimization', 'efficiency'],
  },
  {
    id: 'quarterly-revenue-forecast-work',
    title: 'Dự báo revenue hàng quý',
    description: 'Dự báo revenue cho các quarters tiếp theo',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Dự Báo Tài Chính',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['revenue', 'forecast', 'quarterly'],
  },
  {
    id: 'cost-forecasting-work',
    title: 'Dự báo chi phí',
    description: 'Dự báo costs dựa trên hiring và project plans',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Dự Báo Tài Chính',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['cost', 'forecast', 'planning'],
  },
  {
    id: 'cash-flow-management-work',
    title: 'Theo dõi cash flow',
    description: 'Theo dõi và quản lý cash flow để đảm bảo thanh khoản',
    category: 'Quản Lý Tài Chính',
    subcategory: 'Dự Báo Tài Chính',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['cash-flow', 'liquidity', 'working-capital'],
    relatedLearningIds: ['cash-flow-management-learning'],
  },

  // === 8. QUẢN LÝ RỦI RO & KHỦNG HOẢNG ===
  {
    id: 'risk-assessment-periodic-work',
    title: 'Đánh giá rủi ro định kỳ',
    description: 'Thực hiện đánh giá rủi ro định kỳ cho operations',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['risk', 'assessment', 'periodic'],
  },
  {
    id: 'risk-mitigation-plans-work',
    title: 'Kế hoạch giảm thiểu rủi ro',
    description: 'Xây dựng và triển khai risk mitigation plans',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['risk', 'mitigation', 'planning'],
  },
  {
    id: 'operational-risks-work',
    title: 'Rủi ro vận hành',
    description: 'Quản lý operational risks (key person, capacity, quality)',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['operational-risk', 'capacity', 'quality'],
  },
  {
    id: 'insurance-management-work',
    title: 'Quản lý bảo hiểm',
    description: 'Quản lý insurance coverage cho operations',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Quản Lý Rủi Ro',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['insurance', 'liability', 'coverage'],
  },
  {
    id: 'bcp-plan-work',
    title: 'Xây dựng & duy trì BCP',
    description: 'Xây dựng và duy trì Business Continuity Plan',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Đảm Bảo Hoạt Động Liên Tục',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['bcp', 'continuity', 'disaster-recovery'],
    relatedLearningIds: ['business-continuity-planning-learning'],
  },
  {
    id: 'dr-plan-work',
    title: 'Xây dựng & duy trì DR Plan',
    description: 'Xây dựng và duy trì Disaster Recovery Plan',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Đảm Bảo Hoạt Động Liên Tục',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['disaster-recovery', 'backup', 'continuity'],
    relatedLearningIds: ['disaster-recovery-learning'],
  },
  {
    id: 'bcp-dr-testing-work',
    title: 'Kiểm tra BCP/DR',
    description: 'Thực hiện testing và drills cho BCP/DR plans',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Đảm Bảo Hoạt Động Liên Tục',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['testing', 'drill', 'continuity'],
  },
  {
    id: 'crisis-response-protocol-work',
    title: 'Quy trình xử lý khủng hoảng',
    description: 'Thiết lập crisis response protocols',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Xử Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['crisis', 'response', 'protocol'],
    relatedLearningIds: ['crisis-management-learning'],
  },
  {
    id: 'major-escalation-handling-work',
    title: 'Xử lý escalation lớn',
    description: 'Xử lý các major escalations từ clients',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Xử Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['escalation', 'crisis', 'client'],
    relatedLearningIds: ['escalation-management-learning'],
  },
  {
    id: 'client-dispute-management-work',
    title: 'Quản lý tranh chấp khách hàng',
    description: 'Giải quyết tranh chấp với clients',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Xử Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['dispute', 'client', 'resolution'],
  },
  {
    id: 'crisis-communication-work',
    title: 'Triển khai giao tiếp khủng hoảng',
    description: 'Giao tiếp với teams, clients, stakeholders trong khủng hoảng',
    category: 'Quản Lý Rủi Ro & Khủng Hoảng',
    subcategory: 'Xử Lý Khủng Hoảng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['crisis', 'communication', 'stakeholder'],
    relatedLearningIds: ['crisis-management-learning'],
  },

  // === 9. VẬN HÀNH DỊCH VỤ ===
  {
    id: 'sla-compliance-tracking-work',
    title: 'Theo dõi tuân thủ SLA',
    description: 'Theo dõi SLA compliance cho tất cả clients',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Quản Lý SLA',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['sla', 'compliance', 'monitoring'],
    relatedLearningIds: ['sla-slo-management-learning'],
  },
  {
    id: 'sla-reporting-work',
    title: 'Báo cáo SLA cho khách hàng',
    description: 'Báo cáo SLA performance cho clients định kỳ',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Quản Lý SLA',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['sla', 'reporting', 'client'],
    relatedLearningIds: ['sla-slo-management-learning'],
  },
  {
    id: 'sla-performance-improvement-work',
    title: 'Cải thiện SLA performance',
    description: 'Triển khai initiatives để cải thiện SLA performance',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Quản Lý SLA',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['sla', 'improvement', 'performance'],
    relatedLearningIds: ['sla-slo-management-learning'],
  },
  {
    id: 'escalation-process-work',
    title: 'Quy trình escalation',
    description: 'Thiết lập và duy trì escalation processes',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Xử Lý Vấn Đề Khẩn Cấp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['escalation', 'process', 'incident'],
    relatedLearningIds: ['escalation-management-learning'],
  },
  {
    id: 'critical-issue-resolution-work',
    title: 'Giải quyết vấn đề khẩn cấp của khách hàng',
    description: 'Xử lý các critical issues từ clients',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Xử Lý Vấn Đề Khẩn Cấp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['critical', 'issue', 'resolution'],
    relatedLearningIds: ['escalation-management-learning'],
  },
  {
    id: 'root-cause-analysis-work',
    title: 'Root cause analysis',
    description: 'Thực hiện RCA cho incidents và issues',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Xử Lý Vấn Đề Khẩn Cấp',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['rca', 'root-cause', 'analysis'],
  },
  {
    id: 'post-mortem-facilitation-work',
    title: 'Hỗ trợ post-mortem',
    description: 'Facilitate post-mortem sessions cho major incidents',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Nâng Cao Chất Lượng Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['post-mortem', 'incident', 'learning'],
  },
  {
    id: 'customer-health-tracking-work',
    title: 'Theo dõi customer health',
    description: 'Theo dõi customer health scores và engagement',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Nâng Cao Chất Lượng Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['customer-health', 'monitoring', 'retention'],
  },
  {
    id: 'service-quality-initiatives-work',
    title: 'Sáng kiến cải thiện chất lượng dịch vụ',
    description: 'Triển khai initiatives để cải thiện service quality',
    category: 'Vận Hành Dịch Vụ',
    subcategory: 'Nâng Cao Chất Lượng Dịch Vụ',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['service-quality', 'improvement', 'excellence'],
  },

  // === 10. HỢP ĐỒNG & PHÁP LÝ ===
  {
    id: 'client-contract-negotiation-work',
    title: 'Đàm phán hợp đồng khách hàng',
    description: 'Đàm phán contracts với clients',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Khách Hàng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['contract', 'negotiation', 'client'],
    relatedLearningIds: ['contract-negotiation-learning'],
  },
  {
    id: 'terms-conditions-negotiation-work',
    title: 'Đàm phán điều khoản & điều kiện',
    description: 'Đàm phán terms and conditions của contracts',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Khách Hàng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['terms', 'conditions', 'negotiation'],
    relatedLearningIds: ['contract-negotiation-learning'],
  },
  {
    id: 'contract-approval-work',
    title: 'Phê duyệt hợp đồng',
    description: 'Review và phê duyệt contracts',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Khách Hàng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['contract', 'approval', 'review'],
  },
  {
    id: 'vendor-contract-negotiation-work',
    title: 'Đàm phán hợp đồng vendor',
    description: 'Đàm phán contracts với vendors và suppliers',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Nhà Cung Cấp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['vendor', 'contract', 'negotiation'],
    relatedLearningIds: ['contract-negotiation-learning'],
  },
  {
    id: 'contract-review-work',
    title: 'Review hợp đồng',
    description: 'Review vendor contracts cho compliance',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Nhà Cung Cấp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['contract', 'review', 'vendor'],
  },
  {
    id: 'contract-renewal-management-work',
    title: 'Quản lý gia hạn hợp đồng',
    description: 'Quản lý contract renewals với vendors',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Hợp Đồng Nhà Cung Cấp',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['renewal', 'contract', 'vendor'],
  },
  {
    id: 'legal-dispute-handling-work',
    title: 'Xử lý tranh chấp pháp lý',
    description: 'Xử lý legal disputes và claims',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Tuân Thủ Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['legal', 'dispute', 'resolution'],
  },
  {
    id: 'ip-policy-enforcement-work',
    title: 'Thực thi chính sách IP',
    description: 'Thực thi IP protection policies',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Tuân Thủ Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['ip', 'policy', 'protection'],
  },
  {
    id: 'labor-law-compliance-work',
    title: 'Đảm bảo tuân thủ luật lao động',
    description: 'Đảm bảo tuân thủ labor laws và regulations',
    category: 'Hợp Đồng & Pháp Lý',
    subcategory: 'Tuân Thủ Pháp Lý',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['labor-law', 'compliance', 'hr'],
  },

  // === 11. QUẢN LÝ NĂNG LỰC & DỰ BÁO ===
  {
    id: 'quarterly-demand-forecast-work',
    title: 'Dự báo nhu cầu hàng quý',
    description: 'Dự báo demand cho resources hàng quý',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['demand', 'forecast', 'quarterly'],
    relatedLearningIds: ['demand-forecasting-learning'],
  },
  {
    id: 'pipeline-analysis-work',
    title: 'Phân tích pipeline',
    description: 'Phân tích sales/project pipeline để dự báo capacity needs',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['pipeline', 'analysis', 'forecasting'],
    relatedLearningIds: ['demand-forecasting-learning'],
  },
  {
    id: 'seasonal-demand-planning-work',
    title: 'Seasonal demand planning',
    description: 'Lập kế hoạch cho seasonal fluctuations',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Dự Báo Nhu Cầu',
    status: 'planned',
    hidden: true,
    priority: 'medium',
    tags: ['seasonal', 'demand', 'planning'],
  },
  {
    id: 'capacity-models-work',
    title: 'Capacity models',
    description: 'Xây dựng và duy trì capacity models',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['capacity', 'modeling', 'planning'],
    relatedLearningIds: ['capacity-modeling-learning'],
  },
  {
    id: 'utilization-tracking-work',
    title: 'Theo dõi tỷ lệ sử dụng nguồn lực',
    description: 'Theo dõi và tối ưu tỷ lệ sử dụng nguồn lực',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['utilization', 'tracking', 'optimization'],
    relatedLearningIds: ['capacity-modeling-learning'],
  },
  {
    id: 'bench-management-work',
    title: 'Tối ưu nguồn lực dự phòng',
    description: 'Quản lý nguồn lực dự phòng để minimize costs',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Quản Lý Năng Lực',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['bench', 'idle', 'capacity'],
  },
  {
    id: 'pipeline-based-hiring-forecast-work',
    title: 'Dự báo tuyển dụng dựa trên pipeline',
    description: 'Dự báo hiring needs dựa trên project pipeline',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Kế Hoạch Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['hiring', 'forecast', 'pipeline'],
    relatedLearningIds: ['talent-acquisition-learning'],
  },
  {
    id: 'hiring-timing-decisions-work',
    title: 'Timing decisions cho hiring',
    description: 'Ra quyết định về timing của hiring activities',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Kế Hoạch Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['hiring', 'timing', 'planning'],
    relatedLearningIds: ['talent-acquisition-learning'],
  },
  {
    id: 'hiring-pipeline-management-work',
    title: 'Quản lý hiring pipeline',
    description: 'Quản lý recruitment pipeline để đáp ứng capacity needs',
    category: 'Quản Lý Năng Lực & Dự Báo',
    subcategory: 'Kế Hoạch Tuyển Dụng',
    status: 'planned',
    hidden: true,
    priority: 'high',
    tags: ['hiring', 'pipeline', 'recruitment'],
    relatedLearningIds: ['talent-acquisition-learning'],
  },
];

// Helper functions
export function getStats(type: 'learning' | 'coo', customItems?: RoadmapItem[]): { total: number; completed: number; inProgress: number; planned: number } {
  const items = customItems || (type === 'learning' ? learningRoadmap : cooRoadmap);
  return {
    total: items.length,
    completed: items.filter((item) => item.status === 'completed').length,
    inProgress: items.filter((item) => item.status === 'in-progress').length,
    planned: items.filter((item) => item.status === 'planned').length,
  };
}

export function getItemsByCategory(type: 'learning' | 'coo'): Record<string, RoadmapItem[]> {
  const items = type === 'learning' ? learningRoadmap : cooRoadmap;
  return items.reduce(
    (acc, item) => {
      if (!acc[item.category]) {
        acc[item.category] = [];
      }
      acc[item.category].push(item);
      return acc;
    },
    {} as Record<string, RoadmapItem[]>
  );
}

export function getRecentItems(type: 'learning' | 'coo', limit: number = 5): RoadmapItem[] {
  const items = type === 'learning' ? learningRoadmap : cooRoadmap;
  return items
    .filter((item) => item.status === 'in-progress' || item.status === 'completed')
    .sort((a, b) => {
      const dateA = a.progress?.lastUpdated || a.startDate || '';
      const dateB = b.progress?.lastUpdated || b.startDate || '';
      return dateB.localeCompare(dateA);
    })
    .slice(0, limit);
}
